export const countries = [
  {
  callingCode: '+966',
  cca2: 'SA',
  flag: '🇸🇦',
  name: {
    bg: 'Саудитска Арабия',
    by: 'Саўдаўская Аравія',
    cn: '沙特阿拉伯',
    cz: 'Saudská arábie',
    de: 'Saudi-Arabien',
    ee: 'Saudi Araabia',
    el: 'Σαουδική Αραβία',
    en: 'Saudi Arabia',
    es: 'San Vicente y las Granadinas',
    fr: 'Arabie Saoudite',
    he: 'ערב הסעודית',
    it: 'Arabia Saudita',
    jp: 'サウジア ラビア',
    nl: 'Saoedi-Arabië',
    pl: 'Arabia Saudyjska',
    pt: 'Arábia Saudita',
    ro: 'Arabia Saudită',
    ru: 'Саудовская Аравия',
    ua: 'Саудівська Аравія',
    zh: '沙特阿拉伯',
  },
  phoneMasks: ['# ### ####', '# #### ####'],
},
{
  callingCode: '+973',
  cca2: 'BH',
  flag: '🇧🇭',
  name: {
    bg: 'Бахрейн',
    by: 'Бахрэйн',
    cn: '巴林',
    cz: 'Bahrajn',
    de: 'Bahrain',
    ee: 'Bahrein',
    el: 'Μπαχρέιν',
    en: 'Bahrain',
    es: 'Bahrein',
    fr: 'Bahreïn',
    he: 'בחריין',
    it: 'Bahrein',
    jp: 'バーレーン',
    nl: 'Bahrein',
    pl: 'Bahrajn',
    pt: 'Barém',
    ro: 'Bahrain',
    ru: 'Бахрейн',
    ua: 'Бахрейн',
    zh: '巴林',
  },
  phoneMasks: ['#### ####'],
},
{
  callingCode: '+20',
  cca2: 'EG',
  flag: '🇪🇬',
  name: {
    bg: 'Египет',
    by: 'Егіпет',
    cn: '埃及',
    cz: 'Egypt',
    de: 'Ägypten',
    ee: 'Egiptus',
    el: 'Αίγυπτος',
    en: 'Egypt',
    es: 'Egipto',
    fr: 'Egypte',
    he: 'מצרים',
    it: 'Egitto',
    jp: 'エジプト',
    nl: 'Egypte',
    pl: 'Egipt',
    pt: 'Egipto',
    ro: 'Egipt',
    ru: 'Египет',
    ua: 'Єгипет',
    zh: '埃及',
  },
  phoneMasks: ['### ### ####'],
},
{
  callingCode: '+964',
  cca2: 'IQ',
  flag: '🇮🇶',
  name: {
    bg: 'Ирак',
    by: 'Ірак',
    cn: '伊拉克',
    cz: 'Irák',
    de: 'Irak',
    ee: 'Iraak',
    el: 'Ιράκ',
    en: 'Iraq',
    es: 'Irak',
    fr: 'Irak',
    he: 'עיראק',
    it: 'Iraq',
    jp: 'イラク',
    nl: 'Irak',
    pl: 'Irak',
    pt: 'Iraque',
    ro: 'Irak',
    ru: 'Ирак',
    ua: 'Ірак',
    zh: '伊拉克',
  },
  phoneMasks: ['### ### ####'],
},
{
  callingCode: '+971',
  cca2: 'AE',
  flag: '🇦🇪',
  name: {
    bg: 'Обединени арабски емирства',
    by: 'Абяднаныя Арабскія Эміраты',
    cn: '阿拉伯联合酋长国',
    cz: 'Spojené arabské emiráty',
    de: 'Vereinigte Arabische Emirate',
    ee: 'Araabia Ühendemiraadid',
    el: 'Ηνωμένα Αραβικά Εμιράτα',
    en: 'United Arab Emirates',
    es: 'Emiratos Árabes Unidos',
    fr: 'Emirats Arabes Unis',
    he: 'איחוד האמירויות הערביות',
    it: 'Emirati Arabi Uniti',
    jp: 'アラブ首長国連邦',
    nl: 'Verenigde Arabische Emiraten',
    pl: 'Zjednoczone Emiraty Arabskie',
    pt: 'Emiratos Árabes Unidos',
    ro: 'Emiratele Arabe Unite',
    ru: 'Объединенные Арабские Эмираты',
    ua: "Об'єднані Арабські Емірати",
    zh: '阿拉伯聯合酋長國',
  },
  phoneMasks: ['# ### ####', '## ### ####'],
},

  , {
  callingCode: '+213',
  cca2: 'DZ',
  flag: '🇩🇿',
  name: {
    bg: 'Алжир',
    by: 'Алжыр',
    cn: '阿尔及利亚',
    cz: 'Alžírsko',
    de: 'Algerien',
    ee: 'Alžeeria',
    el: 'Αλγερία',
    en: 'Algeria',
    es: 'Argelia',
    fr: 'Algérie',
    he: "אלג'יריה",
    it: 'Algeria',
    jp: 'アルジェリア',
    nl: 'Algerije',
    pl: 'Algieria',
    pt: 'Argélia',
    ro: 'Algeria',
    ru: 'Алжир',
    ua: 'Алжир',
    zh: '阿爾及利亞',
  },
  phoneMasks: ['## ### ####'],
},
{
  callingCode: '+1',
  cca2: 'US',
  flag: '🇺🇸',
  name: {
    bg: 'Съединени щати',
    by: 'Злучаныя Штаты',
    cn: '美国',
    cz: 'Spojené státy',
    de: 'Vereinigte Staaten',
    ee: 'Ühendriigid',
    el: 'Ηνωμένες Πολιτείες Αμερικής',
    en: 'United States',
    es: 'Estados Unidos',
    fr: 'États-Unis',
    he: 'ארצות הברית',
    it: 'stati Uniti',
    jp: 'アメリカ',
    nl: 'Verenigde Staten',
    pl: 'Stany Zjednoczone',
    pt: 'Estados Unidos',
    ro: 'Statele Unite',
    ru: 'Соединенные Штаты',
    ua: 'Сполучені Штати',
    zh: '美國',
  },
},
{
  callingCode: '+963',
  cca2: 'SY',
  flag: '🇸🇾',
  name: {
    bg: 'Сирийска Арабска Република',
    by: 'Сірыйская Арабская Рэспубліка',
    cn: '阿拉伯叙利亚共和国',
    cz: 'Syrská Arabská republika',
    de: 'Syrische Arabische Republik',
    ee: 'Süüria Araabia Vabariik',
    el: 'Συρία',
    en: 'Syrian Arab Republic',
    es: 'República Árabe Siria',
    fr: 'République arabe syrienne',
    he: 'סוריה',
    it: 'Repubblica Araba Siriana',
    jp: 'シリアアラブ共和国',
    nl: 'Syrische Arabische Republiek',
    pl: 'Republika Syryjsko-Arabska',
    pt: 'Síria',
    ro: 'Republica Araba Siriana',
    ru: 'Сирийская Арабская Республика',
    ua: 'Сирійська Арабська Республіка',
    zh: '阿拉伯敘利亞共和國',
  },
  phoneMasks: ['## #### ###'],
},
{
  callingCode: '+249',
  cca2: 'SD',
  flag: '🇸🇩',
  name: {
    bg: 'Судан',
    by: 'Судан',
    cn: '苏丹',
    cz: 'Súdán',
    de: 'Sudan',
    ee: 'Sudaan',
    el: 'Σουδάν',
    en: 'Sudan',
    es: 'Sudán',
    fr: 'Soudan',
    he: 'סודן',
    it: 'Sudan',
    jp: 'スーダ ン',
    nl: 'Soedan',
    pl: 'Sudan',
    pt: 'Sudão',
    ro: 'Sudan',
    ru: 'Судан',
    ua: 'Судан',
    zh: '蘇丹',
  },
  phoneMasks: ['## ### ####'],
},
{
  callingCode: '+27',
  cca2: 'ZA',
  flag: '🇿🇦',
  name: {
    bg: 'Южна Африка',
    by: 'Паўднёвая Афрыка',
    cn: '南非',
    cz: 'Jižní Afrika',
    de: 'Südafrika',
    ee: 'Lõuna-Aafrika',
    el: 'Νότια Αφρική',
    en: 'South Africa',
    es: 'Sudáfrica',
    fr: 'Afrique du Sud',
    he: 'דרום אפריקה',
    it: 'Sud Africa',
    jp: '南アフリカ',
    nl: 'Zuid-Afrika',
    pl: 'Afryka Południowa',
    pt: 'África do Sul',
    ro: 'Africa de Sud',
    ru: 'Южная Африка',
    ua: 'Південна Африка',
    zh: '南非',
  },
  phoneMasks: ['## ### ####'],
},
{
  callingCode: '+216',
  cca2: 'TN',
  flag: '🇹🇳',
  name: {
    bg: 'Тунис',
    by: 'Туніс',
    cn: '突尼斯',
    cz: 'Tunisko',
    de: 'Tunesien',
    ee: 'Tuneesia',
    el: 'Τυνησία',
    en: 'Tunisia',
    es: 'Túnez',
    fr: 'Tunisie',
    he: 'תוניסיה',
    it: 'Tunisia',
    jp: 'チュニジア',
    nl: 'Tunesië',
    pl: 'Tunezja',
    pt: 'Tunísia',
    ro: 'Tunisia',
    ru: 'Тунис',
    ua: 'Туніс',
    zh: '突尼斯',
  },
  phoneMasks: ['## ### ###'],
},
{
  callingCode: '+90',
  cca2: 'TR',
  flag: '🇹🇷',
  name: {
    bg: 'Турция',
    by: 'Турцыя',
    cn: '火鸡',
    cz: 'Turecko',
    de: 'Türkei',
    ee: 'Türgi',
    el: 'Τουρκία',
    en: 'Turkey',
    es: 'Turquía',
    fr: 'dinde',
    he: 'טורקיה',
    it: 'tacchino',
    jp: '七面鳥',
    nl: 'kalkoen',
    pl: 'Turcja',
    pt: 'Turquia',
    ro: 'Curcan',
    ru: 'Турция',
    ua: 'Туреччина',
    zh: '火雞',
  },
  phoneMasks: ['### ### ####'],
},
{
  callingCode: '+39',
  cca2: 'IT',
  flag: '🇮🇹',
  name: {
    bg: 'Италия',
    by: 'Італія',
    cn: '意大利',
    cz: 'Itálie',
    de: 'Italien',
    ee: 'Itaalia',
    el: 'Ιταλία',
    en: 'Italy',
    es: 'Italia',
    fr: 'Italie',
    he: 'איטליה',
    it: 'Italia',
    jp: 'イタリア',
    nl: 'Italië',
    pl: 'Włochy',
    pt: 'Itália',
    ro: 'Italia',
    ru: 'Италия',
    ua: 'Італія',
    zh: '意大利',
  },
  phoneMasks: ['# ### #####', '### #### ###'],
},
{
  callingCode: '+970',
  cca2: 'PS',
  flag: '🇵🇸',
  name: {
    bg: 'Палестинска територия, окупирана',
    by: 'Палестынская тэрыторыя, акупаваная',
    cn: '被占领的 巴勒斯坦领土',
    cz: 'Palestinské území, obsazené',
    de: 'Besetzte palästinensische Gebiete',
    ee: 'Palestiina territoorium, okupeeritud',
    el: 'Κράτος της Παλαιστίνης',
    en: 'Palestinian Territory, Occupied',
    es: 'Territorio Palestino Ocupado',
    fr: 'Territoire palestinien, occupé',
    he: 'הרשות הפלסטינית',
    it: 'Territori palestinesi occupati',
    jp: 'パレスチナ自治区、占領下',
    nl: 'Palestijns gebied, bezet',
    pl: 'Teretorium Paleństynskie, Okupowane',
    pt: 'Território Palestino, Ocupado',
    ro: 'Teritoriul Palestinian, Ocupat',
    ru: 'Палестинская Территория, Оккупированная',
    ua: 'Палестинська територія, окупована',
    zh: '被占領的巴勒斯坦領土',
  },
  phoneMasks: ['## ### ####'],
},
{
  callingCode: '+33',
  cca2: 'FR',
  flag: '🇫🇷',
  name: {
    bg: 'Франция',
    by: 'Францыя',
    cn: '法国',
    cz: 'Francie',
    de: 'Frankreich',
    ee: 'Prantsusmaa',
    el: 'Γαλλία',
    en: 'France',
    es: 'Francia',
    fr: 'France',
    he: 'צרפת',
    it: 'Francia',
    jp: 'フランス',
    nl: 'Frankrijk',
    pl: 'Francja',
    pt: 'França',
    ro: 'Franţa',
    ru: 'Франция',
    ua: 'Франція',
    zh: '法國',
  },
  phoneMasks: ['### ### ###'],
},
{
  callingCode: '+246',
  cca2: 'IO',
  flag: '🇮🇴',
  name: {
    bg: 'Британска територия в Индийския океан',
    by: 'Брытанская тэрыторыя ў Індыйскім акіяне',
    cn: '英属印度洋领地',
    cz: 'Britské území v Indickém oceánu',
    de: 'Britisches Territorium des Indischen Ozeans',
    ee: 'Briti India ookeani territoorium',
    el: 'Βρετανικά Εδάφη Ινδικού Ωκεανού',
    en: 'British Indian Ocean Territory',
    es: 'Territorio Británico del Océano Índico',
    fr: "Territoire britannique de l'océan Indien",
    he: 'טריטוריית האוקיינוס ​​ההודי הבריטי',
    it: "Territorio britannico dell'Oceano Indiano",
    jp: 'イギリス領インド洋地域',
    nl: 'Brits-Indisch oceaan gebied',
    pl: 'Brytyjskie Terytorium Oceanu Indyjskiego',
    pt: 'Território Britânico do Oceano Índico',
    ro: 'Teritoriul Britanic al Oceanului Indian',
    ru: 'Британская территория Индийского океана',
    ua: 'Британська територія в Індійському океані',
    zh: '英屬印度洋領地',
  },
  phoneMasks: ['## ##### ####'],
},
{
  callingCode: '+965',
  cca2: 'KW',
  flag: '🇰🇼',
  name: {
    bg: 'Кувейт',
    by: 'Кувейт',
    cn: ' 科威特',
    cz: 'Kuvajt',
    de: 'Kuwait',
    ee: 'Kuveit',
    el: 'Κουβέιτ',
    en: 'Kuwait',
    es: 'Kuwait',
    fr: 'Koweit',
    he: 'כווית',
    it: 'Kuwait',
    jp: 'クウェート',
    nl: 'Koeweit',
    pl: 'Kuwejt',
    pt: 'Kuwait',
    ro: 'Kuweit',
    ru: 'Кувейт',
    ua: 'Кувейт',
    zh: '科威特',
  },
  phoneMasks: ['#### ####'],
},
{
  callingCode: '+98',
  cca2: 'IR',
  flag: '🇮🇷',
  name: {
    bg: 'Иран, Ислямска република',
    by: 'Іран, Ісламская Рэспубліка',
    cn: '伊朗伊斯兰共和国',
    cz: 'Írán, Islámská Republika',
    de: 'Iran, Islamische Republik',
    ee: 'Iraan, Iraagi Islamivabariik',
    el: 'Ιράν',
    en: 'Iran, Islamic Republic of',
    es: 'Irán, República Islámica de',
    fr: 'Iran (République islamique d',
    he: 'איראן',
    it: 'Iran (Repubblica Islamica del',
    jp: 'イラン、イスラム共和国',
    nl: 'Iran, Islamitische Republiek',
    pl: 'Iran, Republika Islamska',
    pt: 'Irão',
    ro: 'Iran (Republica Islamica a',
    ru: 'Иран, Исламская Республика',
    ua: 'Іран, Ісламська Республіка',
    zh: '伊朗伊斯蘭共和國',
  },
  phoneMasks: ['### ### ####'],
},
{
  callingCode: '+62',
  cca2: 'ID',
  flag: '🇮🇩',
  name: {
    bg: 'Индонезия',
    by: 'Інданезія',
    cn: '印度尼西亚',
    cz: 'Indonésie',
    de: 'Indonesien',
    ee: 'Indoneesia',
    el: 'Ινδονησία',
    en: 'Indonesia',
    es: 'Indonesia',
    fr: 'Indonésie',
    he: 'אינדונזיה',
    it: 'Indonesia',
    jp: 'インドネシア',
    nl: 'Indonesië',
    pl: 'Indonezja',
    pt: 'Indonésia',
    ro: 'Indonezia',
    ru: 'Индонезия',
    ua: 'Індонезія',
    zh: '印度尼西亞',
  },
  phoneMasks: [
    '## ### ##',
    '## ### ###',
    '## ### ####',
    '### ### ####',
    '### ### ## ###',
  ],
},
{
  callingCode: '+974',
  cca2: 'QA',
  flag: '🇶🇦',
  name: {
    bg: 'Катар',
    by: 'Катар',
    cn: '卡塔尔',
    cz: 'Katar',
    de: 'Katar',
    ee: 'Katar',
    el: 'Κατάρ',
    en: 'Qatar',
    es: 'Qatar',
    fr: 'Qatar',
    he: 'קטאר',
    it: 'Qatar',
    jp: 'カタール',
    nl: 'Qatar',
    pl: 'Katar',
    pt: 'Catar',
    ro: 'Qatar',
    ru: 'Катар',
    ua: 'Катар',
    zh: '卡塔爾',
  },
  phoneMasks: ['#### ####'],
},
{
  callingCode: '+962',
  cca2: 'JO',
  flag: '🇯🇴',
  name: {
    bg: 'Йордания',
    by: 'Іарданія',
    cn: '约旦',
    cz: 'Jordán',
    de: 'Jordanien',
    ee: 'Jordaania',
    el: 'Ιορδανία',
    en: 'Jordan',
    es: 'Jordania',
    fr: 'Jordan',
    he: 'ירדן',
    it: 'Giordania',
    jp: 'ヨルダン',
    nl: 'Jordanië',
    pl: 'Jordania',
    pt: 'Jordânia',
    ro: 'Iordania',
    ru: 'Иордания',
    ua: 'Йорданія',
    zh: '約旦',
  },
  phoneMasks: ['# #### ####'],
},
{
  callingCode: '+967',
  cca2: 'YE',
  flag: '🇾🇪',
  name: {
    bg: 'Йемен',
    by: 'Емен',
    cn: '也门',
    cz: 'Jemen',
    de: 'Jemen',
    ee: 'Jeemen',
    el: 'Υεμένη',
    en: 'Yemen',
    es: 'Yemen',
    fr: 'Yémen',
    he: 'תימן',
    it: 'Yemen',
    jp: ' イエメン',
    nl: 'Jemen',
    pl: 'Jemen',
    pt: 'Iémen',
    ro: 'Yemen',
    ru: 'Йемен',
    ua: 'Ємен',
    zh: '也門',
  },
  phoneMasks: ['# ### ###', '## ### ###', '### ### ###'],
},
]