import { CountryItem } from "../types/Types";

export const countryCodes: CountryItem[] = [
  {
    name: {
      en: "Algeria",
      ru: "Алжир",
      pl: "Algieria",
      ua: "Алжир",
      cz: "Alžírsko",
      by: "Алжыр",
      pt: "Argélia",
      es: "Argelia",
      ro: "Algeria",
      bg: "Алжир",
      de: "Algerien",
      fr: "Algérie",
      nl: "Algerije",
      it: "Algeria",
      cn: "阿尔及利亚",
      zh: "阿爾及利亞",
      ee: "Alžeeria",
      jp: "アルジェリア",
      he: "אלג'יריה",
      el: "Αλγερία",
    },
    dial_code: "+213",
    code: "DZ",
    flag: "🇩🇿",
  },

  {
    name: {
      en: "Bahrain",
      ru: "Бахрейн",
      pl: "Bahrajn",
      ua: "Бахрейн",
      cz: "Bahrajn",
      by: "Бахрэйн",
      pt: "Barém",
      es: "Bahrein",
      ro: "Bahrain",
      bg: "Бахрейн",
      de: "Bahrain",
      fr: "Bahreïn",
      nl: "Bahrein",
      it: "Bahrein",
      cn: "巴林",
      zh: "巴林",
      ee: "Bahrein",
      jp: "バーレーン",
      he: "בחריין",
      el: "Μπαχρέιν",
    },
    dial_code: "+973",
    code: "BH",
    flag: "🇧🇭",
  },
  {
    name: {
      en: "Egypt",
      ru: "Египет",
      pl: "Egipt",
      ua: "Єгипет",
      cz: "Egypt",
      by: "Егіпет",
      pt: "Egipto",
      es: "Egipto",
      ro: "Egipt",
      bg: "Египет",
      de: "Ägypten",
      fr: "Egypte",
      nl: "Egypte",
      it: "Egitto",
      cn: "埃及",
      zh: "埃及",
      ee: "Egiptus",
      jp: "エジプト",
      he: "מצרים",
      el: "Αίγυπτος",
    },
    dial_code: "+20",
    code: "EG",
    flag: "🇪🇬",
  },

  {
    name: {
      en: "France",
      ru: "Франция",
      pl: "Francja",
      ua: "Франція",
      cz: "Francie",
      by: "Францыя",
      pt: "França",
      es: "Francia",
      ro: "Franţa",
      bg: "Франция",
      de: "Frankreich",
      fr: "France",
      nl: "Frankrijk",
      it: "Francia",
      cn: "法国",
      zh: "法國",
      ee: "Prantsusmaa",
      jp: "フランス",
      he: "צרפת",
      el: "Γαλλία",
    },
    dial_code: "+33",
    code: "FR",
    flag: "🇫🇷",
  },

  {
    name: {
      en: "India",
      ru: "Индия",
      pl: "Indie",
      ua: "Індія",
      cz: "Indie",
      by: "Індыя",
      pt: "Índia",
      es: "India",
      ro: "India",
      bg: "Индия",
      de: "Indien",
      fr: "Inde",
      nl: "India",
      it: "India",
      cn: "印度",
      zh: "印度",
      ee: "India",
      jp: "インド",
      he: "הוֹדוּ",
      el: "Ινδία",
    },
    dial_code: "+91",
    code: "IN",
    flag: "🇮🇳",
  },
  {
    name: {
      en: "Indonesia",
      ru: "Индонезия",
      pl: "Indonezja",
      ua: "Індонезія",
      cz: "Indonésie",
      by: "Інданезія",
      pt: "Indonésia",
      es: "Indonesia",
      ro: "Indonezia",
      bg: "Индонезия",
      de: "Indonesien",
      fr: "Indonésie",
      nl: "Indonesië",
      it: "Indonesia",
      cn: "印度尼西亚",
      zh: "印度尼西亞",
      ee: "Indoneesia",
      jp: "インドネシア",
      he: "אינדונזיה",
      el: "Ινδονησία",
    },
    dial_code: "+62",
    code: "ID",
    flag: "🇮🇩",
  },
  {
    name: {
      en: "Iran, Islamic Republic of",
      ru: "Иран, Исламская Республика",
      pl: "Iran, Republika Islamska",
      ua: "Іран, Ісламська Республіка",
      cz: "Írán, Islámská Republika",
      by: "Іран, Ісламская Рэспубліка",
      pt: "Irão",
      es: "Irán, República Islámica de",
      ro: "Iran (Republica Islamica a",
      bg: "Иран, Ислямска република",
      de: "Iran, Islamische Republik",
      fr: "Iran (République islamique d",
      nl: "Iran, Islamitische Republiek",
      it: "Iran (Repubblica Islamica del",
      cn: "伊朗伊斯兰共和国",
      zh: "伊朗伊斯蘭共和國",
      ee: "Iraan, Iraagi Islamivabariik",
      jp: "イラン、イスラム共和国",
      he: "איראן",
      el: "Ιράν",
    },
    dial_code: "+98",
    code: "IR",
    flag: "🇮🇷",
  },
  {
    name: {
      en: "Iraq",
      ru: "Ирак",
      pl: "Irak",
      ua: "Ірак",
      cz: "Irák",
      by: "Ірак",
      pt: "Iraque",
      es: "Irak",
      ro: "Irak",
      bg: "Ирак",
      de: "Irak",
      fr: "Irak",
      nl: "Irak",
      it: "Iraq",
      cn: "伊拉克",
      zh: "伊拉克",
      ee: "Iraak",
      jp: "イラク",
      he: "עיראק",
      el: "Ιράκ",
    },
    dial_code: "+964",
    code: "IQ",
    flag: "🇮🇶",
  },

  {
    name: {
      en: "Italy",
      ru: "Италия",
      pl: "Włochy",
      ua: "Італія",
      cz: "Itálie",
      by: "Італія",
      pt: "Itália",
      es: "Italia",
      ro: "Italia",
      bg: "Италия",
      de: "Italien",
      fr: "Italie",
      nl: "Italië",
      it: "Italia",
      cn: "意大利",
      zh: "意大利",
      ee: "Itaalia",
      jp: "イタリア",
      he: "איטליה",
      el: "Ιταλία",
    },
    dial_code: "+39",
    code: "IT",
    flag: "🇮🇹",
  },

  {
    name: {
      en: "Jordan",
      ru: "Иордания",
      pl: "Jordania",
      ua: "Йорданія",
      cz: "Jordán",
      by: "Іарданія",
      pt: "Jordânia",
      es: "Jordania",
      ro: "Iordania",
      bg: "Йордания",
      de: "Jordanien",
      fr: "Jordan",
      nl: "Jordanië",
      it: "Giordania",
      cn: "约旦",
      zh: "約旦",
      ee: "Jordaania",
      jp: "ヨルダン",
      he: "ירדן",
      el: "Ιορδανία",
    },
    dial_code: "+962",
    code: "JO",
    flag: "🇯🇴",
  },

  {
    name: {
      en: "Korea, Republic of",
      ru: "Республика Корея",
      pl: "Republika Korei",
      ua: "Корея, Республіка",
      cz: "Korea, republika",
      by: "Карэя, Рэспубліка",
      pt: "Coreia do Sul",
      es: "Corea, República de",
      ro: "Republica Coreea",
      bg: "Република Корея",
      de: "Korea, Republik von",
      fr: "Corée, République de",
      nl: "Korea, republiek van",
      it: "Corea, Repubblica di",
      cn: "韩国",
      zh: "韓國",
      ee: "Korea Vabariik",
      jp: "大韓民国",
      he: "קוריאה הדרומית",
      el: "Νότια Κορέα",
    },
    dial_code: "+82",
    code: "KR",
    flag: "🇰🇷",
  },
  {
    name: {
      en: "Kuwait",
      ru: "Кувейт",
      pl: "Kuwejt",
      ua: "Кувейт",
      cz: "Kuvajt",
      by: "Кувейт",
      pt: "Kuwait",
      es: "Kuwait",
      ro: "Kuweit",
      bg: "Кувейт",
      de: "Kuwait",
      fr: "Koweit",
      nl: "Koeweit",
      it: "Kuwait",
      cn: "科威特",
      zh: "科威特",
      ee: "Kuveit",
      jp: "クウェート",
      he: "כווית",
      el: "Κουβέιτ",
    },
    dial_code: "+965",
    code: "KW",
    flag: "🇰🇼",
  },

  {
    name: {
      en: "Lebanon",
      ru: "Ливан",
      pl: "Liban",
      ua: "Ліван",
      cz: "Libanon",
      by: "Ліван",
      pt: "Líbano",
      es: "Líbano",
      ro: "Liban",
      bg: "Ливан",
      de: "Libanon",
      fr: "Liban",
      nl: "Libanon",
      it: "Libano",
      cn: "黎巴嫩的",
      zh: "黎巴嫩的",
      ee: "Liibanon",
      jp: "レバノン",
      he: "לבנון",
      el: "Λίβανος",
    },
    dial_code: "+961",
    code: "LB",
    flag: "🇱🇧",
  },

  {
    name: {
      en: "Libyan Arab Jamahiriya",
      ru: "Ливийская Арабская Джамахирия",
      pl: "Libijska Arabska Dżamahirija",
      ua: "Лівійська Арабська Джамахірія",
      cz: "Libyjský Arab Jamahiriya",
      by: "Лівійская Арабская Джамахірыя",
      pt: "Líbia",
      es: "Jamahiriya Árabe Libia",
      ro: "Jamahiriya arabă libiană",
      bg: "Либийска арабска Джамахирия",
      de: "Libyscher arabischer Jamahiriya",
      fr: "Jamahiriya arabe libyenne",
      nl: "Libië",
      it: "Giamahiria araba libica",
      cn: "阿拉伯利比亚民众国",
      zh: "阿拉伯利比亞民眾國",
      ee: "Liibüa Araabia Jamahiriya",
      jp: "リビアアラブジャマヒリヤ",
      he: "ג'מהיריה הערבית הלובית",
      el: "Λιβύη",
    },
    dial_code: "+218",
    code: "LY",
    flag: "🇱🇾",
  },

  {
    name: {
      en: "Palestinian Territory, Occupied",
      ru: "Палестинская Территория, Оккупированная",
      pl: "Teretorium Paleństynskie, Okupowane",
      ua: "Палестинська територія, окупована",
      cz: "Palestinské území, obsazené",
      by: "Палестынская тэрыторыя, акупаваная",
      pt: "Território Palestino, Ocupado",
      es: "Territorio Palestino Ocupado",
      ro: "Teritoriul Palestinian, Ocupat",
      bg: "Палестинска територия, окупирана",
      de: "Besetzte palästinensische Gebiete",
      fr: "Territoire palestinien, occupé",
      nl: "Palestijns gebied, bezet",
      it: "Territori palestinesi occupati",
      cn: "被占领的巴勒斯坦领土",
      zh: "被占領的巴勒斯坦領土",
      ee: "Palestiina territoorium, okupeeritud",
      jp: "パレスチナ自治区、占領下",
      he: "הרשות הפלסטינית",
      el: "Κράτος της Παλαιστίνης",
    },
    dial_code: "+970",
    code: "PS",
    flag: "🇵🇸",
  },

  {
    name: {
      en: "Qatar",
      ru: "Катар",
      pl: "Katar",
      ua: "Катар",
      cz: "Katar",
      by: "Катар",
      pt: "Catar",
      es: "Qatar",
      ro: "Qatar",
      bg: "Катар",
      de: "Katar",
      fr: "Qatar",
      nl: "Qatar",
      it: "Qatar",
      cn: "卡塔尔",
      zh: "卡塔爾",
      ee: "Katar",
      jp: "カタール",
      he: "קטאר",
      el: "Κατάρ",
    },
    dial_code: "+974",
    code: "QA",
    flag: "🇶🇦",
  },

  {
    name: {
      en: "Saudi Arabia",
      ru: "Саудовская Аравия",
      pl: "Arabia Saudyjska",
      ua: "Саудівська Аравія",
      cz: "Saudská arábie",
      by: "Саўдаўская Аравія",
      pt: "Arábia Saudita",
      es: "San Vicente y las Granadinas",
      ro: "Arabia Saudită",
      bg: "Саудитска Арабия",
      de: "Saudi-Arabien",
      fr: "Arabie Saoudite",
      nl: "Saoedi-Arabië",
      it: "Arabia Saudita",
      cn: "沙特阿拉伯",
      zh: "沙特阿拉伯",
      ee: "Saudi Araabia",
      jp: "サウジアラビア",
      he: "ערב הסעודית",
      el: "Σαουδική Αραβία",
    },
    dial_code: "+966",
    code: "SA",
    flag: "🇸🇦",
  },

  {
    name: {
      en: "South Africa",
      ru: "Южная Африка",
      pl: "Afryka Południowa",
      ua: "Південна Африка",
      cz: "Jižní Afrika",
      by: "Паўднёвая Афрыка",
      pt: "África do Sul",
      es: "Sudáfrica",
      ro: "Africa de Sud",
      bg: "Южна Африка",
      de: "Südafrika",
      fr: "Afrique du Sud",
      nl: "Zuid-Afrika",
      it: "Sud Africa",
      cn: "南非",
      zh: "南非",
      ee: "Lõuna-Aafrika",
      jp: "南アフリカ",
      he: "דרום אפריקה",
      el: "Νότια Αφρική",
    },
    dial_code: "+27",
    code: "ZA",
    flag: "🇿🇦",
  },

  {
    name: {
      en: "Sudan",
      ru: "Судан",
      pl: "Sudan",
      ua: "Судан",
      cz: "Súdán",
      by: "Судан",
      pt: "Sudão",
      es: "Sudán",
      ro: "Sudan",
      bg: "Судан",
      de: "Sudan",
      fr: "Soudan",
      nl: "Soedan",
      it: "Sudan",
      cn: "苏丹",
      zh: "蘇丹",
      ee: "Sudaan",
      jp: "スーダン",
      he: "סודן",
      el: "Σουδάν",
    },
    dial_code: "+249",
    code: "SD",
    flag: "🇸🇩",
  },

  {
    name: {
      en: "Syrian Arab Republic",
      ru: "Сирийская Арабская Республика",
      pl: "Republika Syryjsko-Arabska",
      ua: "Сирійська Арабська Республіка",
      cz: "Syrská Arabská republika",
      by: "Сірыйская Арабская Рэспубліка",
      pt: "Síria",
      es: "República Árabe Siria",
      ro: "Republica Araba Siriana",
      bg: "Сирийска Арабска Република",
      de: "Syrische Arabische Republik",
      fr: "République arabe syrienne",
      nl: "Syrische Arabische Republiek",
      it: "Repubblica Araba Siriana",
      cn: "阿拉伯叙利亚共和国",
      zh: "阿拉伯敘利亞共和國",
      ee: "Süüria Araabia Vabariik",
      jp: "シリアアラブ共和国",
      he: "סוריה",
      el: "Συρία",
    },
    dial_code: "+963",
    code: "SY",
    flag: "🇸🇾",
  },

  {
    name: {
      en: "Tunisia",
      ru: "Тунис",
      pl: "Tunezja",
      ua: "Туніс",
      cz: "Tunisko",
      by: "Туніс",
      pt: "Tunísia",
      es: "Túnez",
      ro: "Tunisia",
      bg: "Тунис",
      de: "Tunesien",
      fr: "Tunisie",
      nl: "Tunesië",
      it: "Tunisia",
      cn: "突尼斯",
      zh: "突尼斯",
      ee: "Tuneesia",
      jp: "チュニジア",
      he: "תוניסיה",
      el: "Τυνησία",
    },
    dial_code: "+216",
    code: "TN",
    flag: "🇹🇳",
  },
  {
    name: {
      en: "Turkey",
      ru: "Турция",
      pl: "Turcja",
      ua: "Туреччина",
      cz: "Turecko",
      by: "Турцыя",
      pt: "Turquia",
      es: "Turquía",
      ro: "Curcan",
      bg: "Турция",
      de: "Türkei",
      fr: "dinde",
      nl: "kalkoen",
      it: "tacchino",
      cn: "火鸡",
      zh: "火雞",
      ee: "Türgi",
      jp: "七面鳥",
      he: "טורקיה",
      el: "Τουρκία",
    },
    dial_code: "+90",
    code: "TR",
    flag: "🇹🇷",
  },
  {
    name: {
      en: "United Arab Emirates",
      ru: "Объединенные Арабские Эмираты",
      pl: "Zjednoczone Emiraty Arabskie",
      ua: "Об'єднані Арабські Емірати",
      cz: "Spojené arabské emiráty",
      by: "Абяднаныя Арабскія Эміраты",
      pt: "Emiratos Árabes Unidos",
      es: "Emiratos Árabes Unidos",
      ro: "Emiratele Arabe Unite",
      bg: "Обединени арабски емирства",
      de: "Vereinigte Arabische Emirate",
      fr: "Emirats Arabes Unis",
      nl: "Verenigde Arabische Emiraten",
      it: "Emirati Arabi Uniti",
      cn: "阿拉伯联合酋长国",
      zh: "阿拉伯聯合酋長國",
      ee: "Araabia Ühendemiraadid",
      jp: "アラブ首長国連邦",
      he: "איחוד האמירויות הערביות",
      el: "Ηνωμένα Αραβικά Εμιράτα",
    },
    dial_code: "+971",
    code: "AE",
    flag: "🇦🇪",
  },

  {
    name: {
      en: "United States",
      ru: "Соединенные Штаты",
      pl: "Stany Zjednoczone",
      ua: "Сполучені Штати",
      cz: "Spojené státy",
      by: "Злучаныя Штаты",
      pt: "Estados Unidos",
      es: "Estados Unidos",
      ro: "Statele Unite",
      bg: "Съединени щати",
      de: "Vereinigte Staaten",
      fr: "États-Unis",
      nl: "Verenigde Staten",
      it: "stati Uniti",
      cn: "美国",
      zh: "美國",
      ee: "Ühendriigid",
      jp: "アメリカ",
      he: "ארצות הברית",
      el: "Ηνωμένες Πολιτείες Αμερικής",
    },
    dial_code: "+1",
    code: "US",
    flag: "🇺🇸",
  },
  {
    name: {
      en: "Yemen",
      ru: "Йемен",
      pl: "Jemen",
      ua: "Ємен",
      cz: "Jemen",
      by: "Емен",
      pt: "Iémen",
      es: "Yemen",
      ro: "Yemen",
      bg: "Йемен",
      de: "Jemen",
      fr: "Yémen",
      nl: "Jemen",
      it: "Yemen",
      cn: "也门",
      zh: "也門",
      ee: "Jeemen",
      jp: "イエメン",
      he: "תימן",
      el: "Υεμένη",
    },
    dial_code: "+967",
    code: "YE",
    flag: "🇾🇪",
  },
];
